#version 460
#extension GL_GOOGLE_include_directive : require

#include "VoxelTerrainCommon.hg"

layout(set = 1, binding = 0, std140) uniform VoxelGenParamsUBO
{
    VoxelTerrainGenParams gp;
} g_VoxelGenParams;

layout(set = 1, binding = 1) writeonly buffer DensityBuffer
{
    float g_OutDensity[];
};

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;
void main()
{
    VoxelTerrainGenParams gp = g_VoxelGenParams.gp;

    uint  dim = gp.samplesPerAxis + 2u * gp.apron; // C+1+2A
    uvec3 tID = gl_GlobalInvocationID;
    if (tID.x >= dim || tID.y >= dim || tID.z >= dim)
        return;

    vec3  worldPos = VoxelTexelToWorld(gp, tID);
    float density  = VoxelTerrainDensity(gp, worldPos);

    g_OutDensity[(tID.z * dim + tID.y) * dim + tID.x] = density;
}
